---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  chartRef:
    kind: OCIRepository
    name: external-secrets
  interval: 1h
  values:
    grafanaDashboard:
      enabled: true
    installCRDs: true
    leaderElect: true
    serviceAccount:
      create: true
      name: external-secrets
    serviceMonitor:
      enabled: true
    webhook:
      replicaCount: 2
