---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./clustergenerator.yaml
- ./clusterrolebinding.yaml
- ./clustersecretstore.yaml
- ./helmrelease.yaml
- ./ocirepository.yaml
