---
ntp_device_tty: "ttyAMA0"
ntp_device_baud: "115200"

ntp_gpsd_devices: "/dev/{{ ntp_device_tty }} /dev/pps0"
ntp_gpsd_options: "-n -s {{ ntp_device_baud }} --badtime"
ntp_gpsd_daemon: "true"

ntp_chrony_subnet: "10.0.0.0/8"

ntp_satpulse_enabled: false
ntp_satpulse_version: "20250516"
