---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-role-arn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: external-dns-role-arn
  data:
  - secretKey: ROLE_ARN
    remoteRef:
      key: k8s/infra/irsa/external-dns
      property: role_arn
