---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns
spec:
  chartRef:
    kind: OCIRepository
    name: external-dns
  interval: 1h
  values:
    fullnameOverride: *app
    provider:
      name: aws
    env:
    - name: AWS_DEFAULT_REGION
      value: "eu-central-1"
    extraArgs:
    - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
    - --crd-source-kind=DNSEndpoint
    - --gateway-name=gateway-external
    - --zone-id-filter=Z08822281XIKHD3V3NF8M
    triggerLoopOnEvent: true
    policy: sync
    sources:
    - crd
    - gateway-httproute
    txtOwnerId: default
    txtPrefix: k8s.%{record_type}-
    domainFilters:
    - youriulbri.ch
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "${ROLE_ARN}"
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: "external-dns-role-arn"
