---
- name: Create manifests directory
  ansible.builtin.file:
    path: /var/lib/rancher/k3s/server/manifests
    state: directory
    owner: root
    group: root
    mode: "0644"

- name: Download vip rbac manifest
  ansible.builtin.get_url:
    url: https://kube-vip.io/manifests/rbac.yaml
    dest: /var/lib/rancher/k3s/server/manifests/vip-rbac.yaml
    owner: root
    group: root
    mode: "0644"

- name: Copy vip manifest
  ansible.builtin.template:
    src: kube-vip.yaml.j2
    dest: /var/lib/rancher/k3s/server/manifests/vip.yaml
    owner: root
    group: root
    mode: "0644"
