---
- name: Restart k3s service
  when:
    - ansible_facts.services['k3s.service'] is defined
    - ansible_facts.services['k3s.service'].state == 'running'
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted

- name: Enable and start k3s service
  when: ansible_facts.services['k3s.service'] is not defined or ansible_facts.services['k3s.service'].state != 'running'
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: started
    enabled: true
