---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: youriulbri-ch
spec:
  dnsNames:
  - youriulbri.ch
  - "*.youriulbri.ch"
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  secretName: youriulbri-ch-tls
  usages:
  - digital signature
