---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: youriulbri-ch-tls
spec:
  secretStoreRefs:
  - name: vault
    kind: ClusterSecretStore
  selector:
    secret:
      name: youriulbri-ch-tls
  template:
    data:
      tls.crt: '{{ index . "tls.crt" | b64enc }}'
      tls.key: '{{ index . "tls.key" | b64enc }}'
  data:
  - match:
      secretKey: &key tls.crt
      remoteRef:
        remoteKey: k8s/tls/youriulbri-ch-tls
        property: *key
  - match:
      secretKey: &key tls.key
      remoteRef:
        remoteKey: k8s/tls/youriulbri-ch-tls
        property: *key
