---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager-role-arn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cert-manager-role-arn
  data:
  - secretKey: ROLE_ARN
    remoteRef:
      key: ansible/k8s/irsa/cert-manager
      property: role_arn
