---
vault_version: 2.6.1
vault_plugins:
  - name: "aws"
    type: "secret"
    image: "ghcr.io/openbao/openbao-plugin-secrets-aws"
    version: "v0.3.1"
    binary_name: "openbao-plugin-secrets-aws"
    sha256: "3eac1f04852876dd1ead9bfd555cafa805af6c87b64b65c3b4a85ff65e98712c"

vault_key_label: "vault1"
vault_aws_root_user: "vault-root"
vault_aws_dns01_user: "vault-dns01"

hsm_user_pin: "{{ vault_hsm_user_pin }}"
