---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg-operator
spec:
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
  interval: 1h
  values:
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
