---
- name: Copy chrony configuration file
  ansible.builtin.template:
    src: "templates/chrony.conf.j2"
    dest: "/etc/chrony/chrony.conf"
    owner: root
    group: root
    mode: 0644

- name: Enable chrony service
  ansible.builtin.service:
    name: chrony
    state: restarted
    enabled: true