---
- name: Install requirements
  ansible.builtin.apt:
    name:
      - pps-tools
      - gpsd
      - gpsd-clients
      - setserial
      - chrony
      - linuxptp
    state: present
    update_cache: true
    
- name: Enable hardware serial and disable console
  ansible.builtin.shell: |
    raspi-config nonint do_serial_hw 0
    raspi-config nonint do_serial_cons 1

- name: "Adjust config.txt for GPS HAT"
  ansible.builtin.lineinfile:
    dest: /boot/firmware/config.txt
    regexp: "^{{ item }}"
    line: '{{ item }}'
  notify: reboot
  with_items: 
    - "dtoverlay=pps-gpio,gpiopin=18,capture_clear"
    - "dtoverlay=disable-bt"
    - "dtparam=uart0=on"
    - "enable_uart=1"

- name: Ensure dynamic tics are disabled in cmdline.txt
  ansible.builtin.replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  notify: reboot
  with_items:
  - "nohz=off"

- name: Ensure no serial console in cmdline.txt
  ansible.builtin.replace:
    path: /boot/firmware/cmdline.txt
    regexp: '^(.*)\b({{ item }})\b(\s+)?(.*)$'
    replace: '\1 \4'
  notify: reboot
  with_items:
    - "console=serial0,115200"

- name: "Add pps-gpio to modules"
  ansible.builtin.lineinfile:
    dest: /etc/modules
    regexp: "^{{ item }}"
    line: '{{ item }}'
  notify: reboot
  with_items: 
    - "pps-gpio"

- name: Disable hciuart service
  ansible.builtin.service:
    name: hciuart
    state: stopped
    enabled: false

- name: Setup gpsd
  ansible.builtin.include_tasks: gpsd.yml

- name: Setup chrony
  ansible.builtin.include_tasks: chrony.yml
  
- name: Start gpsd
  ansible.builtin.service:
    name: gpsd
    state: restarted

- name: Copy grandmaster ptp configuration
  ansible.builtin.copy:
    src: ptp-gm.conf
    dest: /etc/ptp4-gm.conf
    mode: 0644
  notify: reboot

- name: Setup grandmaster services
  include_role:
    name: common
    tasks_from: setup_service
  loop:
    - ptp_nic_coalesce
    - ptp4l-gm
    - phc2sys-gm
  loop_control:
    loop_var: service_name
