---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: towonel-agent
spec:
  endpoints:
  - dnsName: "external.youriulbri.ch"
    recordType: A
    targets:
    - &vps_ip 3.64.182.209
  - dnsName: "towonel.youriulbri.ch"
    recordType: A
    targets:
    - *vps_ip
