---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: towonel-agent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: towonel-agent-secret
  data:
  - secretKey: TOWONEL_INVITE_TOKEN
    remoteRef:
      key: k8s/infra/exit-node
      property: towonel-token
