{
 "title": "SatPulse sky view",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(satpulse_satellite_look_angle_degrees,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sky view",
   "type": "nline-plotlyjs-panel",
   "gridPos": { "h": 27, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "satpulse_satellite_look_angle_degrees{instance=\"${instance:raw}\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "SatPulse signals",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(satpulse_satellite_signal_level_dbhz,instance)"
    }
   },
   {
    "name": "gnss",
    "label": "GNSS",
    "query": {
     "query": "label_values(satpulse_satellite_signal_level_dbhz,gnss)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$gnss signal levels",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "repeat": "gnss",
   "targets": [
    {
     "expr": "satpulse_satellite_signal_level_dbhz{instance=\"${instance:raw}\",gnss=\"$gnss\"}\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}
{
 "title": "SatPulse PHC",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(satpulse_phc_sync_status,instance)"
    }
   },
   { "name": "tau", "label": "𝜏", "query": "20s, 1m,5m,30m,2h,8h,24h" }
  ]
 },
 "panels": [
  { "title": "$instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "satpulse_phc_sync_status{instance=\"${instance:raw}\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status) (satpulse_phc_samples_total{instance=\"${instance:raw}\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frequency adjustment",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(satpulse_phc_frequency_adjustment{instance=\"${instance:raw}\"}[20s]) * 1e9",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PHC Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum(rate(satpulse_phc_offset_abs_seconds_bucket{instance=\"${instance:raw}\"}[$tau])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(satpulse_phc_offset_abs_seconds_bucket{instance=\"${instance:raw}\"}[$tau])) by (le))",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(satpulse_phc_offset_abs_seconds_bucket{instance=\"${instance:raw}\"}[$tau])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "sum(rate(satpulse_phc_offset_abs_seconds_sum{instance=\"${instance:raw}\"}[$tau]))\n/\nsum(rate(satpulse_phc_offset_abs_seconds_count{instance=\"${instance:raw}\"}[$tau]))",
     "legendFormat": "mean"
    },
    {
     "expr": "sqrt(\n  (\n    sum(rate(satpulse_phc_offset_sum_squares_seconds_total{instance=\"${instance:raw}\"}[$tau]))\n    /\n    sum(rate(satpulse_phc_offset_abs_seconds_count{instance=\"${instance:raw}\"}[$tau]))\n  )\n  -\n  (\n    sum(rate(satpulse_phc_offset_abs_seconds_sum{instance=\"${instance:raw}\"}[$tau]))\n    /\n    sum(rate(satpulse_phc_offset_abs_seconds_count{instance=\"${instance:raw}\"}[$tau]))\n  ) ^ 2\n)",
     "legendFormat": "𝜎"
    }
   ]
  }
 ]
}