---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rook-ceph-dashboard
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: rook-ceph-dashboard-password
  data:
  - secretKey: password
    remoteRef:
      key: k8s/namespaces/rook-ceph
      property: password
