---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: rook-ceph-dashboard
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
  - name: vault
    kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: password-gen
  data:
  - match:
      secretKey: password
      remoteRef:
        remoteKey: k8s/apps/rook-ceph
        property: password
