---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: client-id-gen
spec:
  length: 20
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: grafana-oauth-client
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: client-id-gen
  data:
  - match:
      secretKey: password
      remoteRef:
        remoteKey: k8s/authentik/apps/grafana
        property: client-id
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: grafana-oauth-secret
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
    - name: vault
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: password-gen
  data:
  - match:
      secretKey: password
      remoteRef:
        remoteKey: k8s/authentik/apps/grafana
        property: client-secret
