---
- name: reboot
  ansible.builtin.reboot:
      msg: "Reboot initiated"
      connect_timeout: 5
      reboot_timeout: "{{ common_reboot_timeout }}"
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
