---
- name: Check if Cilium is installed
  run_once: true
  ignore_errors: true
  delegate_to: 127.0.0.1
  become: false
  ansible.builtin.command: 
    cmd: kubectl get daemonset cilium -n kube-system
  register: cilium_installed

- name: Install cilium
  run_once: true
  delegate_to: 127.0.0.1
  become: false
  when: cilium_installed.rc != 0
  ansible.builtin.command:
    cmd: "cilium install {{ cilium_values }}"
