---
- name: Add cilium helm repo
  run_once: true
  delegate_to: 127.0.0.1
  become: false
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: "https://helm.cilium.io/"


- name: Deploy Cilium chart
  run_once: true
  delegate_to: 127.0.0.1
  become: false
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    namespace: kube-system
    values:
      k8sServiceHost: "{{ k3s_api_vip }}"
      k8sServicePort: "{{ k3s_api_port }}"
      kubeProxyReplacement: true
      ipam.operator.clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]
