---
- name: Setup k3s and dependencies on cluster nodes
  hosts: k3s_cluster
  gather_facts: true
  become: true

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - jq
          - open-iscsi
          - cryptsetup

    - name: Make sure iscsid is started and enabled
      ansible.builtin.systemd:
        name: iscsid
        state: started
        enabled: true

    - name: Enable the iscsi_tcp module
      community.general.modprobe:
        name: iscsi_tcp
        state: present

    - name: Enable the dm-crypt module
      community.general.modprobe:
        name: dm-crypt
        state: present

- name: Disable and remove dphys-swapfile on rpi cluster nodes
  hosts: "rpi:&k3s_cluster"
  become: true
  tasks:
    - name: Disable dphys-swapfile swap
      ansible.builtin.command: dphys-swapfile swapoff
      ignore_errors: true

    - name: Uninstall dphys-swapfile swap
      ansible.builtin.command: dphys-swapfile uninstall
      ignore_errors: true

    - name: Remove dphys-swapfile from startup
      ansible.builtin.command: update-rc.d dphys-swapfile remove

    - name: Purge dphys-swapfile package
      ansible.builtin.apt:
        name: dphys-swapfile
        state: absent
