---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: unifi-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: unifi-dns-secret
  data:
  - secretKey: UNIFI_API_KEY
    remoteRef:
      key: k8s/unifi
      property: key
