---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: alertmanager-secret
  data:
  - secretKey: DISCORD_WEBHOOK
    remoteRef:
      key: k8s/apps/alertmanager/discord
      property: webhook
  - secretKey: PUSHOVER_USER_KEY
    remoteRef:
      key: k8s/apps/alertmanager/pushover
      property: user-key
  - secretKey: ALERTMANAGER_PUSHOVER_TOKEN
    remoteRef:
      key: k8s/apps/alertmanager/pushover
      property: alertmanager-token
