---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-pg-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault
  target:
    name: authentik-pg-credentials
  data:
  - secretKey: &key username
    remoteRef:
      key: k8s/apps/cloudnative-pg/authentik
      property: *key
  - secretKey: &key password
    remoteRef:
      key: k8s/apps/cloudnative-pg/authentik
      property: *key
