---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-pg-credentials
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
  - name: vault
    kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: password-gen
  template:
    data:
      username: "authentik"
  data:
  - match:
      secretKey: &key username
      remoteRef:
        remoteKey: k8s/namespaces/cloudnative-pg/authentik
        property: *key
  - match:
      secretKey: &key password
      remoteRef:
        remoteKey: k8s/namespaces/cloudnative-pg/authentik
        property: *key
