---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-bootstrap-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
  - secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
    remoteRef:
      key: k8s/namespaces/authentik
      property: bootstrap-token
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
  - secretKey: AUTHENTIK_SECRET_KEY
    remoteRef:
      key: k8s/namespaces/authentik
      property: secret-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-pg-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
  - secretKey: AUTHENTIK_POSTGRESQL__USER
    remoteRef:
      key: k8s/namespaces/cloudnative-pg/authentik
      property: username
  - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
    remoteRef:
      key: k8s/namespaces/cloudnative-pg/authentik
      property: password
