---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-bootstrap-token
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
  - name: vault
    kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: password-gen
  template:
    type: Opaque
    data:
      bootstrap-token: "{{ .password }}"
  data:
  - match:
      secretKey: &key bootstrap-token
      remoteRef:
        remoteKey: k8s/apps/authentik
        property: *key
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-secret-key
spec:
  updatePolicy: IfNotExists
  secretStoreRefs:
  - name: vault
    kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: ClusterGenerator
      name: password-gen
  template:
    type: Opaque
    data:
      secret-key: "{{ .password }}"
  data:
  - match:
      secretKey: &key secret-key
      remoteRef:
        remoteKey: k8s/apps/authentik
        property: *key
