---
pi:
  hosts:
    pinas:
      hostname: pinas
      ip: 10.0.20.150
      ansible_host: 10.0.20.150
      mac: 6c:1f:f7:c6:e0:e0
    pi3:
      hostname: pi3
      ip: 10.0.20.153
      ansible_host: 10.0.20.153
      mac: 2c:cf:67:76:f1:c5
    pi4:
      hostname: pi4
      ip: 10.0.20.154
      ansible_host: 10.0.20.154
      mac: e4:5f:01:c6:a7:9f
vm:
  hosts:
    vm0:
      hostname: vm0
      ip: 10.0.20.170
      ansible_host: 10.0.20.170
    vm1:
      hostname: vm1
      ip: 10.0.20.171
      ansible_host: 10.0.20.171
    vm2:
      hostname: vm2
      ip: 10.0.20.172
      ansible_host: 10.0.20.172
nas:
  hosts:
    pinas:
dns:
  hosts:
    pi3:
vault:
  hosts:
    pi3:
ntp:
  hosts:
    pi4:
vps:
  hosts:
    vps0:
      hostname: vps0
      ip: 3.64.182.209
      ansible_host: 3.64.182.209
      ansible_port: 13737
local:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
