---
all:
  children:
    pi:
      hosts:
        pi0:
          hostname: pi0
          ip: 10.0.20.150
          ansible_host: 10.0.20.150
          mac: 2c:cf:67:1c:b5:f8
        pi1:
          hostname: pi1
          ip: 10.0.20.151
          ansible_host: 10.0.20.151
          mac: 2c:cf:67:2d:e8:d0
        pi2:
          hostname: pi2
          ip: 10.0.20.152
          ansible_host: 10.0.20.152
          mac: 2c:cf:67:96:fe:4d
        pi3:
          hostname: pi3
          ip: 10.0.20.153
          ansible_host: 10.0.20.152
          #mac: 2c:cf:67:
    tiny:
      hosts:
        tiny0:
          hostname: tiny0
          ip: 10.0.20.160
          ansible_host: 10.0.20.160
          mac: 3c:fd:fe:a8:6f:49
        tiny1:
          hostname: tiny1
          ip: 10.0.20.161
          ansible_host: 10.0.20.161
          mac: f8:75:a4:c5:8c:73
        tiny2:
          hostname: tiny2
          ip: 10.0.20.162
          ansible_host: 10.0.20.162
          mac: e8:6a:64:db:38:21
    k3s_cluster:
      children:
        k3s_master:
          hosts:
            pi[0:2]:
        k3s_agent:
          hosts:
            tiny[0:2]:
    vault:
      hosts:
        pi3: