---
- name: Setup docker
  hosts: k3s_agent
  vars:
    docker_edition: 'ce'
    docker_packages_state: 'present'
    docker_install_compose_plugin: true
    docker_compose_package: docker-compose-plugin
    docker_users:
      - "{{ ansible_user }}"
  become: true
  roles:
    - geerlingguy.docker