---
- name: Ensure external resources exist
  hosts: localhost
  gather_facts: true
  vars:
    tf_dir: "../tf"
    tf_bucket: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32616238376638386237376266656439373839623033653030623839633739323132396233663565
          6630326565616433663734333134323335333931386333350a646633353233636365313662653163
          36393963663032393230653161383436356130383530303335343530646630323163326365303035
          6266656561633462660a383534353732326233316663363437313065383633343231363264616363
          39626635343863623464363034626438356365356637306361646539393439326432396235353437
          3834316165613461363332653162643431346136333930386535
    tf_bucket_key: "prod/terraform.tfstate"
  tasks:
    - name: Ensure aws zones
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
      cloud.terraform.terraform:
        project_path: "{{ tf_dir }}"
        complex_vars: true
        force_init: true
        backend_config:
          bucket: "{{ tf_bucket }}"
          key: "{{ tf_bucket_key }}"
        variables:
          domain: "{{ domain }}"
          zones:
            - name: "{{ domain }}"
              subzones:
                - "home"
        state: present

    - name: Ensure certificates exist
      ansible.builtin.command: |
        certbot certonly \
        --dns-route53
        --server https://acme-v02.api.letsencrypt.org/directory \
        --agree-tos \
        --non-interactive \
        --rsa-key-size 4096 \
        -m {{ mail }} \
        -d {{ item }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
      register: certbot_create
      changed_when:
        - certbot_create.rc==0
        - '"Certificate not yet due for renewal; no action taken." not in certbot_create.stdout'
      with_items:
        - "vault.{{ domain }}"
