---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oauth-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  data:
  - secretKey: client-id
    remoteRef:
      key: k8s/namespaces/authentik/provider/grafana
      property: client-id
  - secretKey: client-secret
    remoteRef:
      key: k8s/namespaces/authentik/provider/grafana
      property: client-secret
