---
- name: Upgrade Raspberry Pis
  ansible.builtin.import_playbook: upgrade_rpis.yml

- name: Setup prerequisites for k3s cluster
  ansible.builtin.import_playbook: prerequisites_k3s_cluster.yml

- name: Setup k3s cluster
  ansible.builtin.import_playbook: iruyo.k3s.site

# - name: Setup fluxcd on k3s cluster
#   ansible.builtin.import_playbook: cluster_install_flux.yml
