- name: Upgrade all Raspberry Pis
  hosts: rpi
  gather_facts: true
  become: true

  tasks:
    - name: Perform a dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
