k3s_version: v1.31.4+k3s1
cluster_context: home
token: "zYMTWVa8vM2p0Xv65BSOauZgvPwjiKBnJe7I1R0t+Kqz026jogVjJlRak5dGQbWnXwo6QhdpHY6GZdN/N0PD5g=="
endpoint: 10.0.20.10

server_config_yaml: |-
  tls-san:
  - "{{ endpoint }}"
  disable: traefik
  disable: servicelb
