k3s_version: v1.31.4+k3s1
cluster_context: home
token: "zYMTWVa8vM2p0Xv65BSOauZgvPwjiKBnJe7I1R0t+Kqz026jogVjJlRak5dGQbWnXwo6QhdpHY6GZdN/N0PD5g=="
api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
vip: 10.0.20.10

kube_vip_tag_version: v0.8.7
kube_vip_arp: true

extra_args: >-
  --node-ip={{ ansible_default_ipv4.address }}
  --flannel-iface=eth0

extra_server_args: >-
  {{ extra_args }}
  --tls-san {{ vip }}
  --disable servicelb
  --disable traefik
  --disable local-storage
